### ISSUE TITLE
nit: repo/cg name might be confused

### ISSUE THREAD

**Issue by bkardell** [mnot/interop-cg#3]
Pretty minor nit, and apologize for making it about something bikesheddy, but I just wanted to note/bring to your attention that within WPT is a new (public facing) effort that folks from all of the engine vendors (and others) are contributing to, to find shared goals for the year - it kind of spawned from compat2021, but it is now called interop (so, interop-2022 https://github.com/web-platform-tests/interop-2022/issues).  It seems likely to be confusing if two potentially significant efforts use the same or a very similar name.  

Unfortunately I don't have a better suggestion atm, but it does seem worth noting that this appears to be geared toward things _outside_ of web browsers themselves, so maybe just adding "service" to it or something could help disambiguate?

**Comment by mnot** [comment]
Hi Brian,

Are you concerned about the short name (interop-cg), the full name, or both?

**Comment by mnot** [comment]
I dropped 'Web' and included 'remedies' in the short name - that should distinguish it adequately.
